### ISSUE TITLE
Add Persian Filter List to new apps for Safari

### ISSUE THREAD

**Issue by ahpourani** [MasterKia/iran-hosted-domains#10]
I’ve tested several content blocker apps in Safari, specifically looking for ones that support Persian-language filtering. Currently, only **Adguard** and **Adblock Pro**, offer support for Persian language filtering 

**Safari Optimized App:**
[1Blocker](https://apps.apple.com/us/app/1blocker-ad-blocker/id1365531024)
[Nad](https://apps.apple.com/us/app/nad/id6661016989)
[Wipr 2](https://apps.apple.com/us/app/wipr-2/id1662217862)

I submitted requests to each app developer to consider adding this feature.

**Filter Optimization:**
Both **1Blocker** and **Wipr 2** have optimized their filters according to Safari’s standards, with Wipr 2 showing promising improvements in its upcoming release. one of the developer replied that users should submit feature requests directly to filter licensing dev to encourage faster adoption.

**Performance Impact:**
- **Adguard**’s general ad content blocker size (30 MB) significantly impacts Safari’s performance, reducing speed by approximately 12% according to the Speedometer 3.0 benchmark.
- **1Blocker** (16 MB) has a slightly lesser effect at -9%.
- **Nad**, the lightest at 4 MB, shows no observable performance decrease.

**Specific Filtering Lists:**
- **Adguard**’s tracker lists, while thorough, slow down Safari dramatically.
- Other apps, such as **Nad** and **Wipr 2**, perform well without noticeable slowdowns. Wipr 2 is expected to add new filters soon, enhancing its blocking capabilities without significant performance costs.

**Feature Requests:**
I’ve suggested that **Nad** and **Wipr 2** include Persian-language filtering lists in future updates

Thanks for considering these requests!

**Comment by MasterKia** [comment]
What can I do to help?
