### ISSUE TITLE
A complete domain list

### ISSUE THREAD

**Issue by papampi** [MasterKia/iran-hosted-domains#5]
Since you are making the effort to make this awesome list and after multiple attempts to ask loyalsoldier and v2fly and also singbox to merge their database with Iran domains and also the inability of singbox to use multiple files and ... 

Is it possible to also provide us a full db file with merge of Iran and Loyalsoldier for using in singbox?

**Comment by papampi** [comment]
Nevermind, found [Chocolate4U](https://github.com/Chocolate4U/Iran-sing-box-rules)

**Comment by MasterKia** [comment]
Let me know if there's something I can do.
